version: '3.8'

services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
    restart: always

  mongo-seed:
    build:
      context: ./api-geradorUCs
      dockerfile: Dockerfile-seed
    depends_on:
      - mongo
    command: >
      bash -c "sleep 10 && 
      mongoimport --host mongo --db projeto-geradorUCS --collection ucs --type json --file /data/ucs.json --jsonArray &&
      mongoimport --host mongo --db projeto-geradorUCS --collection docentes --type json --file /data/docentes.json --jsonArray"
    networks:
      - app-network
    restart: "no"

  api-geradorucs:
    build:
      context: ./api-geradorUCs
    ports:
      - "3124:3124"
    depends_on:
      - mongo
      - mongo-seed
    environment:
      - MONGODB_URI=mongodb://mongo:27017/projeto-geradorUCS
    networks:
      - app-network
    restart: always

  html-geradorucs:
    build:
      context: ./html-geradorUCs
    ports:
      - "3125:3125"
    networks:
      - app-network
    restart: always

volumes:
  mongo-data:

networks:
  app-network:
